import { Victim, SuspectData, Evidence, CaseConfig, DifficultyLevel } from '../case.js';

/**
 * The "Truth" of the case generated by the Logic Engine.
 * This contains no flavor text, only raw data and relationships.
 */
export interface CaseSkeleton {
    seed: string;
    theme: string;
    difficulty: DifficultyLevel;

    // Roles
    killerId: string;
    victimId: string;
    suspectIds: string[];

    // The Map (Graph)
    map: Record<string, string[]>;
    rooms: string[];

    // The Plot (What actually happened)
    timeline: TimelineEvent[];
    murderTime: string; // HH:MM
    murderLocation: string; // "kitchen", "study"
    murderWeapon: string; // "knife", "poison"

    // Evidence (Where things are)
    evidenceLocations: Record<string, string>; // "knife": "kitchen"
    dnaLocations: Record<string, string[]>; // "kitchen": ["killer", "victim"]

    suspectArchetypes?: Record<string, SuspectArchetype>;
    relationships?: Relationship[];
    evidenceReasons?: Record<string, string>;
    motiveCategory?: string;
    templateId?: string;
    guildId?: string;
}

export interface TimelineEvent {
    time: number; // minutes from start (e.g. 0 = 10:00 PM)
    formattedTime: string; // "10:00 PM"
    actorId: string;
    action: 'move' | 'wait' | 'interact' | 'kill' | 'leave';
    location: string;
    target?: string; // object or person
    description: string; // "Killer moved to Kitchen"
}

/**
 * Configuration for the Generator
 */
export interface GeneratorConfig {
    theme?: 'noir' | 'modern' | 'mansion';
    difficulty?: 'easy' | 'medium' | 'hard';
    seed?: string;
    useLLM?: boolean;
    templateId?: string;
    guildId?: string;
    onProgress?: (stage: string, detail: string) => void;
}

export interface SuspectArchetype {
    role: string;
    psychProfile: string;
    defaultBehavior: string;
    likelySecretCategory: string;
    nervousTell: string;
}

export interface Relationship {
    a: string;
    b: string;
    dynamic: string;
    tensionLevel: 'low' | 'medium' | 'high';
}
